### ISSUE TITLE
Using WI Zoom and Perspective uncontrollably changes WI Zoom's behavior

### ISSUE THREAD

**Issue by 1unar-Eclipse** [MCLegoMan/Perspective#13]
On Fabric, Minecraft version 1.20.6, mod version 1.2.3.

Got this mod to have held perspective without going all the way for a client, and learned that even without using Perspective's zoom, my other zoom mod (WI Zoom) somehow changed behavior. Specifically, even though I'm using the WI Zoom keybind and have Perspective's zoom completely disabled, adding Perspective made WI Zoom render hand position without considering zoom, while WI Zoom without Perspective made held items "stay in place"; as the camera zoomed in, the items were gradually cut off.

I changed the Zoom Mode option in Perspective to "Spyglass" to attempt to fix the issue, but that setting didn't change this behavior, even on Default. WI Zoom has no options whatsoever.

Both mods:
![image](https://github.com/user-attachments/assets/d21b9b30-faeb-4d26-a393-f75fa9c25326)
Note how, despite the zoom, the hands are the same size as they would be without zoom.

Just WI Zoom:
![image](https://github.com/user-attachments/assets/96f1b05a-0e50-4fa0-b2f7-2a3e4a492522)
Slightly zoomed out for clarity on my point - notice how the held items are slightly cut off.

**Comment by 1unar-Eclipse** [comment]
I played around with Perspective's Zoom settings a bit more to see if I could at least recreate WI Zoom, and that is not the case for a few reasons.
- No setting in Perspective controls behavior of items held as zoom level increases.
- Zoom strength is persistent - if you scroll to change the strength and un-zoom, the strength you were at previously is still used. (WI Zoom resets strength to its default every zoom.)
  - There does not appear to be an option to disable this.

And slightly unrelated: the "Camera Mode" setting is a bit unclear - while I initially assumed it would impact how zoom works, it actually controls sensitivity while zoomed. There is no description in the mod that explains this. (I would change this to "Sensitivity Mode: Original / Reduced".)

**Comment by mclegoman** [comment]
Thanks for reporting this!

As Perspective is in part itself a zoom mod, incompatibility with other zoom mods isn't surprising.
I can add compatibility for WI Zoom and release it sometime next week.

As to the reasons you can't recreate WI Zoom, I'd love to try and add these in v1.3 as they sound like they could be useful.
Speaking of, v1.3 has changed zoom quite a bit, - with the "sensitivity" being reworked completely - adding more options and renaming some to make them more clear. The final release will have hover tooltips on options to make it clearer what they do exactly. v1.3 is however planned to be released for 1.21, but an alpha version for 1.20.5/6 does exist [1.3.0-alpha.6](https://modrinth.com/mod/mclegoman-perspective/version/1.3.0-alpha.6+1.20.5-6), but is a dev build so use at your own risk.

**Comment by mclegoman** [comment]
When `1.3.0-alpha.7 for 1.21.1` releases, it will contain a new config option to disable perspective's zoom (this should help with compatibility with other zoom mods), and an option to reset zoom when releasing the zoom button.
I'll also take a look at adding WI Zoom specific compatibility in this version.

As for 1.20.5/6, `1.2.4 for 1.20.6` will be released soon, it adds an option to the experimental screen called "Disable Zoom", which as the name suggests, should disable Perspective from using it's zoom features.

**Comment by mclegoman** [comment]
https://modrinth.com/mod/mclegoman-perspective/version/W5tZ7Z1Y
