### ISSUE TITLE
Include a cps display option

### ISSUE THREAD

**Issue by Oregano1963** [MCLegoMan/Perspective#18]
Maybe this isn't in the purview of Perspective but an option to display your clicks per second could be useful.

**Comment by mclegoman** [comment]
Added a toggle in [Perspective 1.3.0-alpha.9+1.21.1](https://modrinth.com/mod/mclegoman-perspective/version/1.3.0-alpha.9+1.21.1).

It's basic, but shows Left:Middle:Right cps.
