### ISSUE TITLE
Mixin namespace conflicts with another mod.

### ISSUE THREAD

**Issue by IZeeXeS** [MCLegoMan/Perspective#3]
This mod conflicts with [Perspective Mod Redux](https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux)
![image](https://github.com/MCLegoMan/Perspective/assets/26113218/a49aaf9a-84e0-49a5-8abd-2507858c37fe)

`Developer Note:`
[Perspective Mod Redux](https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux) uses "perspective" as their mixins namespace, instead of using their mod namespace "perspectivemod".

**Comment by mclegoman** [comment]
Thanks for reporting this!
I'll fix this in the next update of Perspective.

In the meantime, from what I can tell this mod is similar and I can confirm works with Perspective.
~~[https://modrinth.com/mod/better-third-person](https://modrinth.com/mod/better-third-person)~~
EDIT: their modrinth hasn't been updated, the newest versions are on curseforge: [https://www.curseforge.com/minecraft/mc-mods/better-third-person](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
