### ISSUE TITLE
more zoom options

### ISSUE THREAD

**Issue by Nettakrim** [MCLegoMan/Perspective#8]
1: currently the FOV difference in each scroll is constant
- this means that the more zoomed in you are, the more the screen appears to zoom, and it makes zooming around 0% really slow
- the ideal curve is `fov = c^zoom`, where c is zoom sensitivity
- - solution: add a button that cycles between zoom modes in the zoom section of configuration: linear and logarithmic

2: pitch and yaw have linear changes with mouse movements
- when really zoomed in it becomes hard to control the mouse, because the changes in pitch and yaw stay the same, they should reduce the more zoomed in you are
- i think the ideal curve is `delta *= c^zoom`
- - solution: add a button that cycles between panning modes in the same screen: linear, logarithmic

3: a change in yaw has less effect at extreme pitches
- when really zoomed in and looking steeply up or down, moving your mouse in a circle moves the camera in a 0 shape, this works fine in normal gameplay, but when youre really zoomed in it feels a bit bad
- the solution is `yaw_delta /= cos(pitch)`, however this causes a division by 0 when looking directly up or down (which is expected if you think about it - its impossible to get lateral movment from yaw at this point, you can only change roll)
- so a reasonable solution is just to do `max(cos(pitch), 0.1)`
- this corrected yaw effect should "fade in" as you get more zoomed in, this can be done by raising the clamp, but a lerp may be more reasonable
- - solution: probably add it onto the 2nd button

these are the 3 things i did in my mod [Spyglass Astronomy](https://modrinth.com/mod/spyglass-astronomy) that make the spyglass zoom nice to use, the first 2 are common in lots of zoom mods, im yet to see another which does the yaw correction

the code for changing mouse sensitivity is prone to being incompatible with some mods, however, since a lot of more popular zoom mods use redirects, or duplicate the entire vanilla behaviour with their adjustments, instead of modifying variables

**Comment by mclegoman** [comment]
[1.3.0-alpha.3](https://modrinth.com/mod/mclegoman-perspective/version/1.3.0-alpha.3+1.20.5) adds logarithmic zoom adjustment, and scaled mouse movements, damage tilt, and view bobbing.

I would like to add `3.` in a future update.

Thanks for the suggestions!

**Comment by mclegoman** [comment]
1.3.0-alpha.7 will contain zoom yaw adjustments :)
